// <auto-generated />
using CodefirstEF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodefirstEF.Migrations
{
    [DbContext(typeof(MyDbcontext))]
    [Migration("20211119101755_addLoai")]
    partial class addLoai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodefirstEF.Models.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .HasColumnType("text");

                    b.HasKey("MaLoai");

                    b.ToTable("Loai");
                });
#pragma warning restore 612, 618
        }
    }
}
